services:
  authz:
    url: http://opa:8181

bundles:
  abi:
    resource: "/v1/bundles/abi"
    service: authz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  console: true
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10

status:
  console: true

plugins:
  discovery:
    name: discovery
    prefix: ""
    decision: discovery/bundle_discovery

default_decision: "/abi/policies/allow"